#IMPLMENTATION OF Artificial Neural Network


# Cleaning the workspace


cat("\f")       # Clear old outputs
rm(list=ls())   # Clear all variables

#-------------------------------------------------------------------------------------------------------------
# HEADER OF THE  OUTPUT
#-------------------------------------------------------------------------------------------------------------
sourceAuthor  <-  "META PRO STAT TEAM"
sourceDate    <-  "01.09.2020"
sourceVersion <-  "1.0.1"

# Inforamtion about the software
print(paste("Info"), quote = FALSE)
print(paste("Date", sourceDate), quote = FALSE)
print(paste("Version", sourceVersion), quote = FALSE)
print(paste("Author", sourceAuthor), quote = FALSE)


# Installing  Packages
# Package for package administration

if(!require("neuralnet")) install.packages("neuralnet") 
library("neuralnet")


## Creating index variable 

# Read the Data

SEPARATOR = ";"  # Separator within the csv.-files

print(paste("Please select Input CSV"), quote = FALSE)

my_data<- read.csv("D:/Studies/DE Project Meta_Prot_Stat/Scripts/German_state_results_New.csv",sep = ";") #Hint: German_state_result 

my_data <- data.matrix(my_data)
head(my_data)


#trainseting and Test Data
n = nrow(my_data)
smp_size <- floor(0.75 * n)
#set.seed(123) 
index<- sample(seq_len(n),size = smp_size)


# creating trainseting and test set
trainsetset <- my_data[index,] 
testset <- my_data[-index,]


#Neural Network
library(neuralnet)
nn <- neuralnet( Result == "1" ~ Mathematics + Biology + History + Litrature + State + City + Wealth, 
                data=trainsetset, hidden=c(4),act.fct = "logistic", linear.output=F, threshold=0.01)
nn
nn$result.matrix
plot(nn)


#Test the resulting output
temp_test <- subset(testset, select = c( "Mathematics" , "Biology", "History",  "Litrature", "State",  "City", "Wealth"))

predicted.nn <- neuralnet::compute(nn, temp_test)
predicted.nn = as.data.frame(predicted.nn)

head(predicted.nn$net.result)
head(testset)

predicted.nn$net.result <- sapply(predicted.nn$net.result,round,digits=0)
print(predicted.nn$net.result)

res <- data.frame("Predicted"=c(predicted.nn$net.result + 2 - (predicted.nn$net.result*2)), "Actual" = c(as.data.frame(testset)$Result) )
print(res)


#RMSE
RMSE(res$Actual,res$Predicted)


#confusion Matrix
#A confusion matrix is used to determine the number of true and false positives generated by our predictions. 
#The model generates 17 true negatives (0's), 20 true positives (1's), 
#while there are 3 false negatives.

table(res$Actual,res$Predicted)
confusionMatrix(as.factor(res$Actual),as.factor(res$Predicted))
