"
NOTE: First Column is treated as 1 in the Selection of Data:

1- Please select the dataset provided with the name 'German_state_results_New') or any avilable numeric data in this form

                   Column(Variable) 1      Column(Variable) 2     . . . .    Column(Variable) n
      
      Row(Instance) 1      (Value)                  (Value)           . . . .         (Value)
      
      Row(Instance) 2      (Value)                  (Value)           . . . .         (Value)
      
      .                       .                        .                                 .
      .                       .                        .                                 .
      .                       .                        .                                 .
      .                       .                        .                                 .
      
      Row(Instance) n      (Value)                  (Value)           . . . .         (Value)
                                        
2- To run the code, select the whole code and run as source (top right in this window) & enter parameters
   which will be asked on running the code in the CONSOLE screen. In this case select:
   
   a- Select Dataset to work on (after screen pops out)
   b- Select what type of activation function you want
   
3- After providing all the parameters, the code will compute following:
   * Computation and Visulaization of Neural Network
   * Comparison of predicted output and corresponding actual test data
   * Confusion Matrix to check false positives etc.
"

# Cleaning the workspace to start over
cat("\f")       # Clear old outputs
rm(list=ls())   # Clear all variables


#------------------------------------------------
"REQUIRED PACKAGES FOR ANN"
#------------------------------------------------

#Cleaning the workplace to start over
cat("\f")       #Clear old outputs
rm(list=ls())   #Clear all variables

#Installing  Packages
if(!require("neuralnet")) install.packages("neuralnet") #For using Neural network package
if(!require("caret")) install.packages("caret")         #For confusion matrix

library("neuralnet")
library("caret")

#------------------------------------------------
"SELECTION OF DATASET AND PARAMETERS"
#------------------------------------------------

print(paste("Please select Input CSV"), quote = FALSE)

#choose file
fname <- file.choose()
#Choose the Separator for file
ask_sep <- as.character(readline(prompt = "ENTER the SEPARATOR for file(',' or ';') : ")) #hint ";"
data_csv <- read.csv(fname, header = TRUE, sep = ask_sep)
matrix <- data.matrix(data_csv)
head(matrix)

cat("\f")       # Clear old outputs

#taking user's input for activation function
actfct <- as.character(readline(prompt = "Enter either of the activation functions you like to use. 'tanh' or 'logistic': "))


#------------------------------------------------
"Train-Test Data Split"
#------------------------------------------------

n = nrow(matrix)
smp_size <- floor(0.75 * n)
index<- sample(seq_len(n),size = smp_size)

#Breaking into Training and Testing Sets:
TrainingSet <- matrix[index,] 
TestingSet <- matrix[-index,]


#------------------------------------------------
"Neural Network Creation"
#------------------------------------------------

library(neuralnet)
nn <- neuralnet( Result == "1" ~ Mathematics + Biology + History + Litrature + State + City + Wealth, 
                 data=TrainingSet, hidden=c(4,2),act.fct = actfct, linear.output=F, threshold=0.01)
nn
nn$result.matrix
plot(nn)

#Test the resulting output
predicted.nn <- neuralnet::compute(nn, TestingSet)
predicted.nn = as.data.frame(predicted.nn)

head(predicted.nn$net.result)  #predicted output
head(TestingSet)                  #TestingSet, with which we will compare the predicted output

predicted.nn$net.result <- sapply(predicted.nn$net.result,round,digits=0) #rounding off the predicted output
print(predicted.nn$net.result)

#Adding and Multiplying with 2 to make all the '0's in predicted results to be '2' 
#so to compare with '2's in the Actual result
res <- data.frame("Predicted"=c(predicted.nn$net.result + 2 - (predicted.nn$net.result*2)), 
                  "Actual" = c(as.data.frame(TestingSet)$Result) )
print(res)

#RMSE
RMSE(res$Actual,res$Predicted)

#------------------------------------------------
"Confusion Matrix"
#------------------------------------------------

#A confusion matrix is used to determine the number of true and false positives 
#generated by our predictions. 
confusionMatrix(as.factor(res$Actual),as.factor(res$Predicted))


print(paste("FINISHED"), quote = FALSE)
