"
1- Please select the dataset provided with the name 'German_state_results_New')
                                        
2- To run the code, select the whole code and run as source (top right in this window) & enter parameters
   which will be asked on running the code in the CONSOLE screen. In this case select:
   
   a- Select Dataset to work on (after screen pops out)
   b- Select what type of activation function you want
   
3- After providing all the parameters, the code will compute following:
   * Computation and Visulaization of Neural Network
   * Comparison of predicted output and corresponding actual test data
   * Confusion Matrix to check false positives etc.
"

# Cleaning the workspace to start over
cat("\f")       # Clear old outputs
rm(list=ls())   # Clear all variables


#------------------------------------------------
"REQUIRED PACKAGES FOR ANN"
#------------------------------------------------

#Cleaning the workplace to start over
cat("\f")       #Clear old outputs
rm(list=ls())   #Clear all variables

#Installing  Packages
if(!require("neuralnet")) install.packages("neuralnet") 
if(!require("caret")) install.packages("caret") 

library("neuralnet")
library("caret")

#------------------------------------------------
"SELECTION OF DATASET AND PARAMETERS"
#------------------------------------------------

SEPARATOR = ";"  # Separator within the csv.-files
print(paste("Please select Input CSV"), quote = FALSE)

fname <- file.choose()
data_csv <- read.csv(fname, header = TRUE, sep = ';')
matrix <- data.matrix(data_csv)
head(matrix)

cat("\f")       # Clear old outputs

#taking user's input for acctivation function
actfct <- as.character(readline(prompt = "Enter either of the activation functions you like to use. 'tanh' or 'logistic': "))


#------------------------------------------------
"Train-Test Data Split"
#------------------------------------------------

n = nrow(matrix)
smp_size <- floor(0.75 * n)
index<- sample(seq_len(n),size = smp_size)

#Breaking into Training and Testing Sets:
TrainingSet <- matrix[index,] 
TestingSet <- matrix[-index,]


#------------------------------------------------
"Neural Network Creation"
#------------------------------------------------

library(neuralnet)
nn <- neuralnet( Result == "1" ~ Mathematics + Biology + History + Litrature + State + City + Wealth, 
                 data=TrainingSet, hidden=c(4,2),act.fct = actfct, linear.output=F, threshold=0.01)
nn
nn$result.matrix
plot(nn)

#Test the resulting output
predicted.nn <- neuralnet::compute(nn, TestingSet)
predicted.nn = as.data.frame(predicted.nn)

head(predicted.nn$net.result)  #predicted output
head(TestingSet)                  #TestingSet, with which we will compare the predicted output

predicted.nn$net.result <- sapply(predicted.nn$net.result,round,digits=0) #rounding off the predicted output
print(predicted.nn$net.result)

#Adding and Multiplying with 2 to make all the '0's in predicted results to be '2' 
#so to compare with '2's in the Actual result
res <- data.frame("Predicted"=c(predicted.nn$net.result + 2 - (predicted.nn$net.result*2)), 
                  "Actual" = c(as.data.frame(TestingSet)$Result) )
print(res)

#RMSE
RMSE(res$Actual,res$Predicted)

cat("\f")       #Clear old outputs
#------------------------------------------------
"Confusion Matrix"
#------------------------------------------------

#A confusion matrix is used to determine the number of true and false positives 
#generated by our predictions. 
table(res$Actual,res$Predicted)

cat("\f")       #Clear old outputs
confusionMatrix(as.factor(res$Actual),as.factor(res$Predicted))



print(paste("FINISHED"), quote = FALSE)
