
#-------------------------------------------------------------------------------------------------------------
                                              " Artificial Neural Network"
#-------------------------------------------------------------------------------------------------------------

cat("\f")       # Clear old outputs
rm(list=ls())   # Clear all variables


#------------------------------------------------
                                          "HEADER OF THE SOFTWARE & INPUT"
#------------------------------------------------


# Installing  Packages

# Package for package administration
if(!require("neuralnet")) install.packages("neuralnet") 
if(!require("caret")) install.packages("caret") 

library("neuralnet")
library("caret")


# Read the Data
SEPARATOR = ";"  # Separator within the csv.-files

print(paste("Please select Input CSV"), quote = FALSE)

data <- file.choose()
data_csv <- read.csv(data, header = TRUE, sep = ';')
my_data <- data.matrix(data_csv)
head(my_data)


#------------------------------------------------
                                                "Train-Test Data Split"
#------------------------------------------------


n = nrow(my_data)
smp_size <- floor(0.75 * n)
#set.seed(123) 
index<- sample(seq_len(n),size = smp_size)


# creating training set and test set
trainsetset <- my_data[index,] 
testset <- my_data[-index,]


#------------------------------------------------
                                      "Neural Network Creation"
#------------------------------------------------

library(neuralnet)
nn <- neuralnet( Result == "1" ~ Mathematics + Biology + History + Litrature + State + City + Wealth, 
                data=trainsetset, hidden=c(4,2),act.fct = "logistic", linear.output=F, threshold=0.01)
nn
nn$result.matrix
plot(nn)


#Test the resulting output
predicted.nn <- neuralnet::compute(nn, testset)
predicted.nn = as.data.frame(predicted.nn)

head(predicted.nn$net.result)
head(testset)

predicted.nn$net.result <- sapply(predicted.nn$net.result,round,digits=0)
print(predicted.nn$net.result)

#Adding and Multiplying with 2 to make all the '0's in predicted results to be '2' 
#so to compare with '2's in the Actual result
res <- data.frame("Predicted"=c(predicted.nn$net.result + 2 - (predicted.nn$net.result*2)), 
                  "Actual" = c(as.data.frame(testset)$Result) )
print(res)


#RMSE
RMSE(res$Actual,res$Predicted)


#------------------------------------------------
                                                  "Confusion Matrix"
#------------------------------------------------

#A confusion matrix is used to determine the number of true and false positives generated by our predictions. 

table(res$Actual,res$Predicted)
confusionMatrix(as.factor(res$Actual),as.factor(res$Predicted))
#https://www.dataschool.io/simple-guide-to-confusion-matrix-terminology/


#Finished
